// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRPCService is an autogenerated mock type for the IRPCService type
type IRPCService struct {
	mock.Mock
}

type mockConstructorTestingTNewIRPCService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRPCService creates a new instance of IRPCService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRPCService(t mockConstructorTestingTNewIRPCService) *IRPCService {
	mock := &IRPCService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
