package constants

const (
	MONGO_TOKEN_DB = "TOKENDB"
	// collection names
	TOKEN          = "TOKEN"
	TOKEN_TRANSFER = "TOKEN_TRANSFER"
	TOKEN_BALANCE  = "TOKEN_BALANCE"
	TOKEN_ERROR    = "TOKEN_ERROR"

	//balance snapshot
	BALANCE_SNAPSHOT_COLLECTION  = "BALANCE_SNAPSHOT"
	TOKEN_TRANSFER_V1_COLLECTION = "TOKEN_TRANSFER"
)
