package constants

const (
	TOKEN_TYPE_UNKNOWN    = "UNKNOWN"
	TOKEN_TYPE_ERC20      = "ERC20"
	TOKEN_TYPE_ERC721     = "ERC721"
	TOKEN_TYPE_ERC1155    = "ERC1155"
	TOKEN_TYPE_BASE_TOKEN = "BASE_TOKEN"
)

const (
	TOKEN_TRANSFER_TYPE_UNKNOWN  = "UNKNOWN"
	TOKEN_TRANSFER_TYPE_MINT     = "MINT"
	TOKEN_TRANSFER_TYPE_BURN     = "BURN"
	TOKEN_TRANSFER_TYPE_TRANSFER = "TRANSFER"
)